# Permalinks
permalink:           pretty

# Setup
title:               Erick Durán
tagline:             ''
description:         'A personal blog dedicated to my free time.'
url:                 https://erickduran.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Erick Durán
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
