# Permalinks
permalink:           pretty

# Setup
title:               Erick Durán
tagline:             'A personal blog'
description:         'A personal blog dedicated to my free time.'
baseurl:             ''
paginate:            5
plugins:             [jekyll-paginate]
logo:                '/public/logo.png'

nav:
  Home:           
    - '/'
  Index:           
    - '/contents/'
    - { Categories: '/categories/' }
    - { Tags: '/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

# About/contact
author:
  name:              Erick Durán
  url:               https://erickduran.com
  email:             me@erickduran.com

# Custom vars
blog_url:            https://blog.erickduran.com

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
